#NAME: Darshini Gupta
#ID: 004928411
#EMAIL: darshinigupta0711@gmail.com

files = lab3b.py README Makefile 

default:
	cp lab3b.py lab3b
	chmod +x lab3b lab3b.py
clean:
	rm -rf lab3b
	rm -rf lab3b-004928411.tar.gz

dist:
	tar -czvf lab3b-004928411.tar.gz $(files)

