#NAME:Darshini Gupta
#EMAIL: darshinigupta0711@gmail.com
#ID: 004928411
files = README Makefile copy.png build_run.png git.png my_beaglebone.jpg connected.png

clean:
	rm -rf  lab4a-004928411.tar.gz

dist:
	tar -czvf lab4a-004928411.tar.gz $(files)
