#NAME: Darshini Gupta
#ID: 004928411
#EMAIL: darshinigupta0711@gmail.com

files = lab3a.c README Makefile ext2_fs.h

default:
	gcc -Wall -Wextra -g -o lab3a lab3a.c
clean:
	rm -rf lab3a
	rm -rf lab3a-004928411.tar.gz

dist:
	tar -czvf lab3a-004928411.tar.gz $(files)

